// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

public partial class CollectAgentDBContext : DbContext
{
    public CollectAgentDBContext(DbContextOptions<CollectAgentDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblAccount> TblAccounts { get; set; }

    public virtual DbSet<TblAdmin> TblAdmins { get; set; }

    public virtual DbSet<TblBlncTrnsAct> TblBlncTrnsActs { get; set; }

    public virtual DbSet<TblBranch> TblBranches { get; set; }

    public virtual DbSet<TblCompany> TblCompanies { get; set; }

    public virtual DbSet<TblDebtTrnsAct> TblDebtTrnsActs { get; set; }

    public virtual DbSet<TblDepositOrder> TblDepositOrders { get; set; }

    public virtual DbSet<TblDepositTrnx> TblDepositTrnxes { get; set; }

    public virtual DbSet<TblDirction> TblDirctions { get; set; }

    public virtual DbSet<TblDistrict> TblDistricts { get; set; }

    public virtual DbSet<TblDrawer> TblDrawers { get; set; }

    public virtual DbSet<TblDrwerTransAction> TblDrwerTransActions { get; set; }

    public virtual DbSet<TblGovernate> TblGovernates { get; set; }

    public virtual DbSet<TblOrder> TblOrders { get; set; }

    public virtual DbSet<TblProdCat> TblProdCats { get; set; }

    public virtual DbSet<TblProdType> TblProdTypes { get; set; }

    public virtual DbSet<TblProduct> TblProducts { get; set; }

    public virtual DbSet<TblProvType> TblProvTypes { get; set; }

    public virtual DbSet<TblProvider> TblProviders { get; set; }

    public virtual DbSet<TblProviderAccOrBank> TblProviderAccOrBanks { get; set; }

    public virtual DbSet<TblRegistration> TblRegistrations { get; set; }

    public virtual DbSet<TblServOrder> TblServOrders { get; set; }

    public virtual DbSet<TblServProduct> TblServProducts { get; set; }

    public virtual DbSet<TblServProvReg> TblServProvRegs { get; set; }

    public virtual DbSet<TblServTrnx> TblServTrnxes { get; set; }

    public virtual DbSet<TblStatus> TblStatuses { get; set; }

    public virtual DbSet<TblStatusReason> TblStatusReasons { get; set; }

    public virtual DbSet<TblTransType> TblTransTypes { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    public virtual DbSet<TblUserType> TblUserTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Arabic_CI_AI");

        modelBuilder.Entity<TblAccount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblAccou__3214EC074332D8A8");

            entity.Property(e => e.AllwdCrdtLmt).HasDefaultValue(0);
            entity.Property(e => e.Code).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Indebtedness).HasDefaultValue(0);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.ParentAccountIdFkNavigation).WithMany(p => p.InverseParentAccountIdFkNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblAccoun__Paren__44FF419A");

            entity.HasOne(d => d.UserIdFkNavigation).WithMany(p => p.TblAccounts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblAccoun__User___440B1D61");
        });

        modelBuilder.Entity<TblAdmin>(entity =>
        {
            entity.Property(e => e.FullName).UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.Password).UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.UserName).UseCollation("Arabic_100_CI_AI");

            entity.HasOne(d => d.AdminProfileFkNavigation).WithMany(p => p.TblAdmins)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblAdmin_tblUserType");
        });

        modelBuilder.Entity<TblBlncTrnsAct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblBlncT__3214EC0797D0600C");

            entity.Property(e => e.Description)
                .HasDefaultValueSql("((0))")
                .UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.RecvrBlncAftr).HasDefaultValue(0);
            entity.Property(e => e.RecvrBlncBfr).HasDefaultValue(0);
            entity.Property(e => e.ReferenceCode).HasDefaultValueSql("((0))");
            entity.Property(e => e.SendrBlncAftr).HasDefaultValue(0);
            entity.Property(e => e.SendrBlncBfr).HasDefaultValue(0);
            entity.Property(e => e.TransTypeId).HasDefaultValue(1);

            entity.HasOne(d => d.ProdidFkNavigation).WithMany(p => p.TblBlncTrnsActs).HasConstraintName("FK_tblBlncTrnsAct_tblProduct");

            entity.HasOne(d => d.RecvrReg).WithMany(p => p.TblBlncTrnsActRecvrRegs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblBlncTrnsAct_tblRegistratiion");

            entity.HasOne(d => d.RecvrUser).WithMany(p => p.TblBlncTrnsActRecvrUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblBlncTrnsAct_tblUser2");

            entity.HasOne(d => d.SendrReg).WithMany(p => p.TblBlncTrnsActSendrRegs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblBlncTr__AccID__412EB0B6");

            entity.HasOne(d => d.SendrUser).WithMany(p => p.TblBlncTrnsActSendrUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblBlncTrnsAct_tblUser1");

            entity.HasOne(d => d.TransType).WithMany(p => p.TblBlncTrnsActs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblBlncTrnsAct_tblTransType");

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblBlncTrnsActUserFkNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblBlncTrnsAct_tblUser");
        });

        modelBuilder.Entity<TblBranch>(entity =>
        {
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.CompanyFkNavigation).WithMany(p => p.TblBranches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblBranch_tblBranch");
        });

        modelBuilder.Entity<TblCompany>(entity =>
        {
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<TblDebtTrnsAct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblDebtT__3214EC07C6B4FF6D");

            entity.Property(e => e.AccidColFromFk).HasDefaultValue(0);
            entity.Property(e => e.BlncTrnsAct).HasDefaultValue(0);
            entity.Property(e => e.ColToDbtAftr).HasDefaultValue(0);
            entity.Property(e => e.ColToDbtBfr).HasDefaultValue(0);
            entity.Property(e => e.Description).UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.ReferenceCode)
                .HasDefaultValueSql("((0))")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.TransTypeId).HasDefaultValue(2);

            entity.HasOne(d => d.AccidColFromFkNavigation).WithMany(p => p.TblDebtTrnsActAccidColFromFkNavigations).HasConstraintName("FK__tblDebtTr__Accid__47DBAE45");

            entity.HasOne(d => d.AccidColToFkNavigation).WithMany(p => p.TblDebtTrnsActAccidColToFkNavigations).HasConstraintName("FK_tblDebtTrnsAct_tblAccount");

            entity.HasOne(d => d.ProvidFkNavigation).WithMany(p => p.TblDebtTrnsActs).HasConstraintName("FK_tblDebtTrnsAct_tblProvider");

            entity.HasOne(d => d.TransType).WithMany(p => p.TblDebtTrnsActs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDebtTrnsAct_tblTransType");

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblDebtTrnsActs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDebtTrnsAct_tblUser");
        });

        modelBuilder.Entity<TblDepositOrder>(entity =>
        {
            entity.Property(e => e.DepositAccNo).HasDefaultValueSql("((0))");
            entity.Property(e => e.DepositFor).HasDefaultValue(0);
            entity.Property(e => e.DepositPhoto).HasDefaultValueSql("((0))");
            entity.Property(e => e.ProviderIdFk).HasDefaultValue(0);
            entity.Property(e => e.ReferenceCode).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.DepositForNavigation).WithMany(p => p.TblDepositOrderDepositForNavigations).HasConstraintName("FK_tblDepositOrder_tblUser1");

            entity.HasOne(d => d.ProviderIdFkNavigation).WithMany(p => p.TblDepositOrders).HasConstraintName("FK_tblDepositOrder_tblProvider");

            entity.HasOne(d => d.Status).WithMany(p => p.TblDepositOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDepositOrder_tblStatus");

            entity.HasOne(d => d.UserIdFkNavigation).WithMany(p => p.TblDepositOrderUserIdFkNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDepositOrder_tblUser");
        });

        modelBuilder.Entity<TblDepositTrnx>(entity =>
        {
            entity.Property(e => e.DepositAccNo).HasDefaultValueSql("((0))");
            entity.Property(e => e.DepositFor).HasDefaultValue(0);
            entity.Property(e => e.DepositPhoto).HasDefaultValueSql("((0))");
            entity.Property(e => e.Description).UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.ProviderId).HasDefaultValue(0);
            entity.Property(e => e.ReferenceCode).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.DepositForNavigation).WithMany(p => p.TblDepositTrnxDepositForNavigations).HasConstraintName("FK_tblDepositTrnx_tblUser1");

            entity.HasOne(d => d.Provider).WithMany(p => p.TblDepositTrnxes).HasConstraintName("FK_tblDepositTrnx_tblProvider");

            entity.HasOne(d => d.StatusIdFkNavigation).WithMany(p => p.TblDepositTrnxes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDepositTrnx_tblStatus");

            entity.HasOne(d => d.UserIdFkNavigation).WithMany(p => p.TblDepositTrnxUserIdFkNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDepositTrnx_tblUser");
        });

        modelBuilder.Entity<TblDirction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblDirct__3214EC07E74083C1");

            entity.Property(e => e.DistrectFk).HasDefaultValue(0);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RouteName)
                .HasDefaultValueSql("((0))")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.DistrectFkNavigation).WithMany(p => p.TblDirctions).HasConstraintName("FK__tblDircti__Distr__30F848ED");

            entity.HasOne(d => d.GovernateFkNavigation).WithMany(p => p.TblDirctions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblDircti__Gover__300424B4");
        });

        modelBuilder.Entity<TblDistrict>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblDistr__3214EC0729D0ED3D");

            entity.Property(e => e.DistrictName).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.GovernateFkNavigation).WithMany(p => p.TblDistricts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblDistri__Gover__2D27B809");
        });

        modelBuilder.Entity<TblDrawer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblDrawe__3214EC078F55B7F4");

            entity.Property(e => e.Code)
                .HasDefaultValueSql("((0))")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Le10).HasDefaultValue(0);
            entity.Property(e => e.Le100).HasDefaultValue(0);
            entity.Property(e => e.Le20).HasDefaultValue(0);
            entity.Property(e => e.Le200).HasDefaultValue(0);
            entity.Property(e => e.Le5).HasDefaultValue(0);
            entity.Property(e => e.Le50).HasDefaultValue(0);
            entity.Property(e => e.TtlAmntOwned).HasDefaultValue(0);

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblDrawers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblDrawer__User___4AB81AF0");
        });

        modelBuilder.Entity<TblDrwerTransAction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblDrwer__3214EC07778A4950");

            entity.Property(e => e.After10).HasDefaultValue(0);
            entity.Property(e => e.After100).HasDefaultValue(0);
            entity.Property(e => e.After20).HasDefaultValue(0);
            entity.Property(e => e.After200).HasDefaultValue(0);
            entity.Property(e => e.After5).HasDefaultValue(0);
            entity.Property(e => e.After50).HasDefaultValue(0);
            entity.Property(e => e.DateAndTime).HasDefaultValueSql("((0))");
            entity.Property(e => e.Le10).HasDefaultValue(0);
            entity.Property(e => e.Le100).HasDefaultValue(0);
            entity.Property(e => e.Le20).HasDefaultValue(0);
            entity.Property(e => e.Le200).HasDefaultValue(0);
            entity.Property(e => e.Le5).HasDefaultValue(0);
            entity.Property(e => e.Le50).HasDefaultValue(0);
            entity.Property(e => e.Own10).HasDefaultValue(0);
            entity.Property(e => e.Own100).HasDefaultValue(0);
            entity.Property(e => e.Own20).HasDefaultValue(0);
            entity.Property(e => e.Own200).HasDefaultValue(0);
            entity.Property(e => e.Own5).HasDefaultValue(0);
            entity.Property(e => e.Own50).HasDefaultValue(0);
            entity.Property(e => e.RefCode)
                .HasDefaultValueSql("((0))")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.TransTypeId).HasDefaultValue(2);
            entity.Property(e => e.TtlAmntAfter).HasDefaultValue(0);
            entity.Property(e => e.TtlAmntOwned).HasDefaultValue(0);
            entity.Property(e => e.TtlAmntTrnsAct).HasDefaultValue(0);

            entity.HasOne(d => d.DrawerIdFkNavigation).WithMany(p => p.TblDrwerTransActions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblDrwerT__Drawe__4D94879B");

            entity.HasOne(d => d.TransType).WithMany(p => p.TblDrwerTransActions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblDrwerTransAction_tblTransType");
        });

        modelBuilder.Entity<TblGovernate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblGover__3214EC07C6084019");

            entity.Property(e => e.GovernateName).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<TblOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblOrder__3214EC07519BD511");

            entity.Property(e => e.OrderNo)
                .HasDefaultValueSql("((0))")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.ProdidFkNavigation).WithMany(p => p.TblOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblOrder__Prodid__3E52440B");

            entity.HasOne(d => d.RegidFkNavigation).WithMany(p => p.TblOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblOrder__Regid___3D5E1FD2");

            entity.HasOne(d => d.StatusFkNavigation).WithMany(p => p.TblOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblOrder_tblStatus");

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblOrder_tblUser");
        });

        modelBuilder.Entity<TblProduct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblProdu__3214EC073F4C8A0B");

            entity.Property(e => e.ProductCode).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ProductName).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.ProviderFkNavigation).WithMany(p => p.TblProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblProduc__Provi__267ABA7A");

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblProduct_tblUser");
        });

        modelBuilder.Entity<TblProvider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblProvi__3214EC075FD0E059");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ProvMainColor).UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.ProviderCode).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ProviderLogo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ProviderName).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ProviderNo).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.ProvTypeFkNavigation).WithMany(p => p.TblProviders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblProvider_tblProvType");
        });

        modelBuilder.Entity<TblProviderAccOrBank>(entity =>
        {
            entity.HasOne(d => d.ProviderFkNavigation).WithMany(p => p.TblProviderAccOrBanks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblProviderAccOrBank_tblProvider");
        });

        modelBuilder.Entity<TblRegistration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblRegis__3214EC0726179942");

            entity.Property(e => e.AccNameNo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Code).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.ProviderFkNavigation).WithMany(p => p.TblRegistrations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblRegist__Provi__3A81B327");

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblRegistrations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblRegist__User___398D8EEE");
        });

        modelBuilder.Entity<TblServOrder>(entity =>
        {
            entity.Property(e => e.Fees).HasDefaultValue(0);
            entity.Property(e => e.OrderNo)
                .HasDefaultValueSql("((0))")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.ServProdFkNavigation).WithMany(p => p.TblServOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServOrder_tblServProduct");

            entity.HasOne(d => d.StatusFkNavigation).WithMany(p => p.TblServOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServOrder_tblStatus");

            entity.HasOne(d => d.UserIdFkNavigation).WithMany(p => p.TblServOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServOrder_tblUser");
        });

        modelBuilder.Entity<TblServProduct>(entity =>
        {
            entity.Property(e => e.ServProdBalance).HasDefaultValue(0);
            entity.Property(e => e.ServProdBuyComm).HasDefaultValue(0m);
            entity.Property(e => e.ServProdBuyPrice).HasDefaultValue(0m);
            entity.Property(e => e.ServProdCode).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ServProdFees).HasDefaultValue(0m);
            entity.Property(e => e.ServProdName).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ServProdSellComm).HasDefaultValue(0m);
            entity.Property(e => e.ServProdSellPrice).HasDefaultValue(0m);

            entity.HasOne(d => d.CategoryFkNavigation).WithMany(p => p.TblServProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServiceProduct_tblProdCat");

            entity.HasOne(d => d.ServProvFkNavigation).WithMany(p => p.TblServProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServProduct_tblProvider");

            entity.HasOne(d => d.TypeFkNavigation).WithMany(p => p.TblServProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServiceProduct_tblProdType");

            entity.HasOne(d => d.UserIdFkNavigation).WithMany(p => p.TblServProducts).HasConstraintName("FK_tblServProduct_tblUser");
        });

        modelBuilder.Entity<TblServProvReg>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tblProviderReg");

            entity.Property(e => e.Code).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ServNo).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.ServProvFkNavigation).WithMany(p => p.TblServProvRegs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServProvReg_tblProvider");

            entity.HasOne(d => d.UserFkNavigation).WithMany(p => p.TblServProvRegs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblProviderReg_tblUser");
        });

        modelBuilder.Entity<TblServTrnx>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tblServicesTrans");

            entity.Property(e => e.BlncAmntOrderTrx).HasDefaultValue(0);
            entity.Property(e => e.Description).UseCollation("Arabic_100_CI_AI");
            entity.Property(e => e.FeesTrx).HasDefaultValue(0);

            entity.HasOne(d => d.RecvrUser).WithMany(p => p.TblServTrnxRecvrUsers).HasConstraintName("FK_tblServTrnx_tblUser1");

            entity.HasOne(d => d.SenderUser).WithMany(p => p.TblServTrnxSenderUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServTrnx_tblUser");

            entity.HasOne(d => d.SendrReg).WithMany(p => p.TblServTrnxes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServTrnx_tblServProvReg");

            entity.HasOne(d => d.ServProdFkNavigation).WithMany(p => p.TblServTrnxes).HasConstraintName("FK_tblServTrnx_tblServProduct");

            entity.HasOne(d => d.StatusFkNavigation).WithMany(p => p.TblServTrnxes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblServTrnx_tblStatus");
        });

        modelBuilder.Entity<TblStatusReason>(entity =>
        {
            entity.HasOne(d => d.StatusIdFkNavigation).WithMany(p => p.TblStatusReasons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblStatusReason_tblStatus");
        });

        modelBuilder.Entity<TblUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblUser__3214EC072F715B92");

            entity.HasIndex(e => e.UserName, "IX_tblUser_UserName").HasFilter("([UserName] IS NOT NULL)");

            entity.Property(e => e.Address).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ContactNo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Email).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.FullName).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Naid).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Password).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Photo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.Street).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.UserName).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.BranchFkNavigation).WithMany(p => p.TblUsers).HasConstraintName("FK_tblUser_tblBranch");

            entity.HasOne(d => d.CompanyFkNavigation).WithMany(p => p.TblUsers).HasConstraintName("FK_tblUser_tblCompany");

            entity.HasOne(d => d.DirctionFkNavigation).WithMany(p => p.TblUsers).HasConstraintName("FK__tblUser__Dirctio__36B12243");

            entity.HasOne(d => d.DistrectFkNavigation).WithMany(p => p.TblUsers).HasConstraintName("FK__tblUser__Distrec__33D4B598");

            entity.HasOne(d => d.GovernateFkNavigation).WithMany(p => p.TblUsers).HasConstraintName("FK__tblUser__Governa__34C8D9D1");

            entity.HasOne(d => d.UserTypeFkNavigation).WithMany(p => p.TblUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tblUser__UserTyp__35BCFE0A");
        });

        modelBuilder.Entity<TblUserType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblUserT__3214EC0737F7CBDA");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UserTypeName).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}