// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblAdmin")]
[Index("AdminProfileFk", Name = "IX_tblAdmin_AdminProfile_FK")]
public partial class TblAdmin
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [Column("AdminProfile_FK")]
    public int AdminProfileFk { get; set; }

    [Required]
    [StringLength(50)]
    public string UserName { get; set; }

    [Required]
    [StringLength(256)]
    public string Password { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("AdminProfileFk")]
    [InverseProperty("TblAdmins")]
    public virtual TblUserType AdminProfileFkNavigation { get; set; }
}