// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblAccount")]
[Index("ParentAccountIdFk", Name = "IX_tblAccount_ParentAccountID_FK")]
[Index("UserIdFk", Name = "IX_tblAccount_UserID_FK")]
public partial class TblAccount
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [Column("UserID_FK")]
    public int UserIdFk { get; set; }

    public int? Indebtedness { get; set; }

    public int? AllwdCrdtLmt { get; set; }

    [Column("ParentAccountID_FK")]
    public int ParentAccountIdFk { get; set; }

    public DateOnly StartDate { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("ParentAccountIdFkNavigation")]
    public virtual ICollection<TblAccount> InverseParentAccountIdFkNavigation { get; set; } = new List<TblAccount>();

    [ForeignKey("ParentAccountIdFk")]
    [InverseProperty("InverseParentAccountIdFkNavigation")]
    public virtual TblAccount ParentAccountIdFkNavigation { get; set; }

    [InverseProperty("AccidColFromFkNavigation")]
    public virtual ICollection<TblDebtTrnsAct> TblDebtTrnsActAccidColFromFkNavigations { get; set; } = new List<TblDebtTrnsAct>();

    [InverseProperty("AccidColToFkNavigation")]
    public virtual ICollection<TblDebtTrnsAct> TblDebtTrnsActAccidColToFkNavigations { get; set; } = new List<TblDebtTrnsAct>();

    [ForeignKey("UserIdFk")]
    [InverseProperty("TblAccounts")]
    public virtual TblUser UserIdFkNavigation { get; set; }
}