// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblBranch")]
[Index("CompanyFk", Name = "IX_tblBranch_Company_FK")]
public partial class TblBranch
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(15)]
    public string ContactNo { get; set; }

    [StringLength(250)]
    public string Address { get; set; }

    [Column("Company_FK")]
    public int CompanyFk { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("CompanyFk")]
    [InverseProperty("TblBranches")]
    public virtual TblCompany CompanyFkNavigation { get; set; }

    [InverseProperty("BranchFkNavigation")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}