// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblBlncTrnsAct")]
[Index("ProdidFk", Name = "IX_tblBlncTrnsAct_Prodid_FK")]
[Index("RecvrRegId", Name = "IX_tblBlncTrnsAct_RecvrRegID")]
[Index("RecvrUserId", Name = "IX_tblBlncTrnsAct_RecvrUserID")]
[Index("ReferenceCode", Name = "IX_tblBlncTrnsAct_ReferenceCode")]
[Index("SendrRegId", Name = "IX_tblBlncTrnsAct_SendrRegID")]
[Index("SendrUserId", Name = "IX_tblBlncTrnsAct_SendrUserID")]
[Index("TransDate", Name = "IX_tblBlncTrnsAct_TransDate")]
[Index("TransTypeId", Name = "IX_tblBlncTrnsAct_TransTypeID")]
[Index("UserFk", Name = "IX_tblBlncTrnsAct_User_FK")]
public partial class TblBlncTrnsAct
{
    [Key]
    public int Id { get; set; }

    [Column("User_FK")]
    public int UserFk { get; set; }

    [Required]
    [StringLength(50)]
    public string ReferenceCode { get; set; }

    [Column("SendrUserID")]
    public int SendrUserId { get; set; }

    [Column("SendrRegID")]
    public int SendrRegId { get; set; }

    [Column("RecvrUserID")]
    public int RecvrUserId { get; set; }

    [Column("RecvrRegID")]
    public int RecvrRegId { get; set; }

    public int BlncTrnsfr { get; set; }

    public int? SendrBlncBfr { get; set; }

    public int? SendrBlncAftr { get; set; }

    public int? RecvrBlncBfr { get; set; }

    public int? RecvrBlncAftr { get; set; }

    public DateOnly TransDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAndTime { get; set; }

    [Column("Prodid_FK")]
    public int? ProdidFk { get; set; }

    [Column("TransTypeID")]
    public int TransTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [ForeignKey("ProdidFk")]
    [InverseProperty("TblBlncTrnsActs")]
    public virtual TblProduct ProdidFkNavigation { get; set; }

    [ForeignKey("RecvrRegId")]
    [InverseProperty("TblBlncTrnsActRecvrRegs")]
    public virtual TblRegistration RecvrReg { get; set; }

    [ForeignKey("RecvrUserId")]
    [InverseProperty("TblBlncTrnsActRecvrUsers")]
    public virtual TblUser RecvrUser { get; set; }

    [ForeignKey("SendrRegId")]
    [InverseProperty("TblBlncTrnsActSendrRegs")]
    public virtual TblRegistration SendrReg { get; set; }

    [ForeignKey("SendrUserId")]
    [InverseProperty("TblBlncTrnsActSendrUsers")]
    public virtual TblUser SendrUser { get; set; }

    [ForeignKey("TransTypeId")]
    [InverseProperty("TblBlncTrnsActs")]
    public virtual TblTransType TransType { get; set; }

    [ForeignKey("UserFk")]
    [InverseProperty("TblBlncTrnsActUserFkNavigations")]
    public virtual TblUser UserFkNavigation { get; set; }
}