// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblCompany")]
public partial class TblCompany
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Logo { get; set; }

    [StringLength(15)]
    public string ContactNo { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("CompanyFkNavigation")]
    public virtual ICollection<TblBranch> TblBranches { get; set; } = new List<TblBranch>();

    [InverseProperty("CompanyFkNavigation")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}