// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDepositTrnx")]
[Index("DepositFor", Name = "IX_tblDepositTrnx_DepositFor")]
[Index("ProviderId", Name = "IX_tblDepositTrnx_ProviderID")]
[Index("StatusIdFk", Name = "IX_tblDepositTrnx_StatusID_FK")]
[Index("UserIdFk", Name = "IX_tblDepositTrnx_UserID_FK")]
public partial class TblDepositTrnx
{
    [Key]
    public int Id { get; set; }

    [Column("UserID_FK")]
    public int UserIdFk { get; set; }

    [StringLength(50)]
    public string ReferenceCode { get; set; }

    [Column("ProviderID")]
    public int? ProviderId { get; set; }

    [StringLength(50)]
    public string DepositAccNo { get; set; }

    public DateOnly Date { get; set; }

    [StringLength(255)]
    public string DepositPhoto { get; set; }

    public int DepositAmount { get; set; }

    [Column("LE500")]
    public int? Le500 { get; set; }

    [Column("LE200")]
    public int? Le200 { get; set; }

    [Column("LE100")]
    public int? Le100 { get; set; }

    [Column("LE50")]
    public int? Le50 { get; set; }

    [Column("LE20")]
    public int? Le20 { get; set; }

    [Column("LE10")]
    public int? Le10 { get; set; }

    [Column("LE5")]
    public int? Le5 { get; set; }

    public int? DepositFor { get; set; }

    public int DepositType { get; set; }

    [Column("StatusID_FK")]
    public int StatusIdFk { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [ForeignKey("DepositFor")]
    [InverseProperty("TblDepositTrnxDepositForNavigations")]
    public virtual TblUser DepositForNavigation { get; set; }

    [ForeignKey("ProviderId")]
    [InverseProperty("TblDepositTrnxes")]
    public virtual TblProvider Provider { get; set; }

    [ForeignKey("StatusIdFk")]
    [InverseProperty("TblDepositTrnxes")]
    public virtual TblStatus StatusIdFkNavigation { get; set; }

    [ForeignKey("UserIdFk")]
    [InverseProperty("TblDepositTrnxUserIdFkNavigations")]
    public virtual TblUser UserIdFkNavigation { get; set; }
}