// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDrwerTransAction")]
[Index("DrawerIdFk", Name = "IX_tblDrwerTransAction_DrawerID_FK")]
[Index("TransTypeId", Name = "IX_tblDrwerTransAction_TransTypeID")]
public partial class TblDrwerTransAction
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string RefCode { get; set; }

    [Column("DrawerID_FK")]
    public int DrawerIdFk { get; set; }

    public int? Own500 { get; set; }

    public int? Own200 { get; set; }

    public int? Own100 { get; set; }

    public int? Own50 { get; set; }

    public int? Own20 { get; set; }

    public int? Own10 { get; set; }

    public int? Own5 { get; set; }

    public int? TtlAmntOwned { get; set; }

    [Column("LE500")]
    public int? Le500 { get; set; }

    [Column("LE200")]
    public int? Le200 { get; set; }

    [Column("LE100")]
    public int? Le100 { get; set; }

    [Column("LE50")]
    public int? Le50 { get; set; }

    [Column("LE20")]
    public int? Le20 { get; set; }

    [Column("LE10")]
    public int? Le10 { get; set; }

    [Column("LE5")]
    public int? Le5 { get; set; }

    public int? TtlAmntTrnsAct { get; set; }

    public int? After500 { get; set; }

    public int? After200 { get; set; }

    public int? After100 { get; set; }

    public int? After50 { get; set; }

    public int? After20 { get; set; }

    public int? After10 { get; set; }

    public int? After5 { get; set; }

    public int? TtlAmntAfter { get; set; }

    public DateOnly TransDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAndTime { get; set; }

    [Column("TransTypeID")]
    public int TransTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [ForeignKey("DrawerIdFk")]
    [InverseProperty("TblDrwerTransActions")]
    public virtual TblDrawer DrawerIdFkNavigation { get; set; }

    [ForeignKey("TransTypeId")]
    [InverseProperty("TblDrwerTransActions")]
    public virtual TblTransType TransType { get; set; }
}