// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDirction")]
[Index("DistrectFk", Name = "IX_tblDirction_Distrect_FK")]
[Index("GovernateFk", Name = "IX_tblDirction_Governate_FK")]
public partial class TblDirction
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string RouteName { get; set; }

    [Column("Governate_FK")]
    public int GovernateFk { get; set; }

    [Column("Distrect_FK")]
    public int? DistrectFk { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("DistrectFk")]
    [InverseProperty("TblDirctions")]
    public virtual TblDistrict DistrectFkNavigation { get; set; }

    [ForeignKey("GovernateFk")]
    [InverseProperty("TblDirctions")]
    public virtual TblGovernate GovernateFkNavigation { get; set; }

    [InverseProperty("DirctionFkNavigation")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}