// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDebtTrnsAct")]
[Index("AccidColFromFk", Name = "IX_tblDebtTrnsAct_AccidColFrom_FK")]
[Index("AccidColToFk", Name = "IX_tblDebtTrnsAct_AccidColTo_FK")]
[Index("ProvidFk", Name = "IX_tblDebtTrnsAct_Provid_FK")]
[Index("ReferenceCode", Name = "IX_tblDebtTrnsAct_ReferenceCode")]
[Index("TransDate", Name = "IX_tblDebtTrnsAct_TransDate")]
[Index("TransTypeId", Name = "IX_tblDebtTrnsAct_TransTypeID")]
[Index("UserFk", Name = "IX_tblDebtTrnsAct_User_FK")]
public partial class TblDebtTrnsAct
{
    [Key]
    public int Id { get; set; }

    [Column("User_FK")]
    public int UserFk { get; set; }

    [Required]
    [StringLength(50)]
    public string ReferenceCode { get; set; }

    [Column("AccidColTo_FK")]
    public int? AccidColToFk { get; set; }

    [Column("AccidColFrom_FK")]
    public int? AccidColFromFk { get; set; }

    public int AmntTrnsAct { get; set; }

    public int? BlncTrnsAct { get; set; }

    public int? ColToDbtBfr { get; set; }

    public int? ColToDbtAftr { get; set; }

    public int? ColFrmDbtBefr { get; set; }

    public int? ColfrmDebtAfter { get; set; }

    public DateOnly TransDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAndTime { get; set; }

    [Column("Provid_FK")]
    public int? ProvidFk { get; set; }

    [Column("TransTypeID")]
    public int TransTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [ForeignKey("AccidColFromFk")]
    [InverseProperty("TblDebtTrnsActAccidColFromFkNavigations")]
    public virtual TblAccount AccidColFromFkNavigation { get; set; }

    [ForeignKey("AccidColToFk")]
    [InverseProperty("TblDebtTrnsActAccidColToFkNavigations")]
    public virtual TblAccount AccidColToFkNavigation { get; set; }

    [ForeignKey("ProvidFk")]
    [InverseProperty("TblDebtTrnsActs")]
    public virtual TblProvider ProvidFkNavigation { get; set; }

    [ForeignKey("TransTypeId")]
    [InverseProperty("TblDebtTrnsActs")]
    public virtual TblTransType TransType { get; set; }

    [ForeignKey("UserFk")]
    [InverseProperty("TblDebtTrnsActs")]
    public virtual TblUser UserFkNavigation { get; set; }
}