// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDrawer")]
[Index("UserFk", Name = "IX_tblDrawer_User_FK")]
public partial class TblDrawer
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Code { get; set; }

    [Column("User_FK")]
    public int UserFk { get; set; }

    [Column("LE500")]
    public int? Le500 { get; set; }

    [Column("LE200")]
    public int? Le200 { get; set; }

    [Column("LE100")]
    public int? Le100 { get; set; }

    [Column("LE50")]
    public int? Le50 { get; set; }

    [Column("LE20")]
    public int? Le20 { get; set; }

    [Column("LE10")]
    public int? Le10 { get; set; }

    [Column("LE5")]
    public int? Le5 { get; set; }

    public int? TtlAmntOwned { get; set; }

    public DateOnly? StartDate { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("DrawerIdFkNavigation")]
    public virtual ICollection<TblDrwerTransAction> TblDrwerTransActions { get; set; } = new List<TblDrwerTransAction>();

    [ForeignKey("UserFk")]
    [InverseProperty("TblDrawers")]
    public virtual TblUser UserFkNavigation { get; set; }
}