// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDistrict")]
[Index("GovernateFk", Name = "IX_tblDistrict_Governate_FK")]
public partial class TblDistrict
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string DistrictName { get; set; }

    [Column("Governate_FK")]
    public int GovernateFk { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("GovernateFk")]
    [InverseProperty("TblDistricts")]
    public virtual TblGovernate GovernateFkNavigation { get; set; }

    [InverseProperty("DistrectFkNavigation")]
    public virtual ICollection<TblDirction> TblDirctions { get; set; } = new List<TblDirction>();

    [InverseProperty("DistrectFkNavigation")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}