// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblDepositOrder")]
[Index("DepositFor", Name = "IX_tblDepositOrder_DepositFor")]
[Index("ProviderIdFk", Name = "IX_tblDepositOrder_ProviderID_FK")]
[Index("StatusId", Name = "IX_tblDepositOrder_StatusID")]
[Index("UserIdFk", Name = "IX_tblDepositOrder_UserID_FK")]
public partial class TblDepositOrder
{
    [Key]
    public int Id { get; set; }

    [Column("UserID_FK")]
    public int UserIdFk { get; set; }

    [StringLength(50)]
    public string ReferenceCode { get; set; }

    [Column("ProviderID_FK")]
    public int? ProviderIdFk { get; set; }

    [StringLength(50)]
    public string DepositAccNo { get; set; }

    public DateOnly Date { get; set; }

    [StringLength(255)]
    public string DepositPhoto { get; set; }

    public int DepositAmount { get; set; }

    [Column("LE500")]
    public int? Le500 { get; set; }

    [Column("LE200")]
    public int? Le200 { get; set; }

    [Column("LE100")]
    public int? Le100 { get; set; }

    [Column("LE50")]
    public int? Le50 { get; set; }

    [Column("LE20")]
    public int? Le20 { get; set; }

    [Column("LE10")]
    public int? Le10 { get; set; }

    [Column("LE5")]
    public int? Le5 { get; set; }

    public int? DepositFor { get; set; }

    public int DepositType { get; set; }

    [Column("StatusID")]
    public int StatusId { get; set; }

    [ForeignKey("DepositFor")]
    [InverseProperty("TblDepositOrderDepositForNavigations")]
    public virtual TblUser DepositForNavigation { get; set; }

    [ForeignKey("ProviderIdFk")]
    [InverseProperty("TblDepositOrders")]
    public virtual TblProvider ProviderIdFkNavigation { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("TblDepositOrders")]
    public virtual TblStatus Status { get; set; }

    [ForeignKey("UserIdFk")]
    [InverseProperty("TblDepositOrderUserIdFkNavigations")]
    public virtual TblUser UserIdFkNavigation { get; set; }
}