// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblGovernate")]
public partial class TblGovernate
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string GovernateName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("GovernateFkNavigation")]
    public virtual ICollection<TblDirction> TblDirctions { get; set; } = new List<TblDirction>();

    [InverseProperty("GovernateFkNavigation")]
    public virtual ICollection<TblDistrict> TblDistricts { get; set; } = new List<TblDistrict>();

    [InverseProperty("GovernateFkNavigation")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}