// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblOrder")]
[Index("OrderNo", Name = "IX_tblOrder_OrderNo")]
[Index("ProdidFk", Name = "IX_tblOrder_Prodid_FK")]
[Index("RegidFk", Name = "IX_tblOrder_Regid_FK")]
[Index("StatusFk", Name = "IX_tblOrder_Status_FK")]
[Index("UserFk", Name = "IX_tblOrder_User_FK")]
public partial class TblOrder
{
    [Key]
    public int Id { get; set; }

    [Column("User_FK")]
    public int UserFk { get; set; }

    [Required]
    [StringLength(50)]
    public string OrderNo { get; set; }

    [Column("Regid_FK")]
    public int RegidFk { get; set; }

    [Column("Prodid_FK")]
    public int ProdidFk { get; set; }

    public int IndebtBefore { get; set; }

    public int BlncAmntOrder { get; set; }

    public int IndebtAfter { get; set; }

    public DateOnly TransDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAndTime { get; set; }

    [Column("Status_FK")]
    public int StatusFk { get; set; }

    [ForeignKey("ProdidFk")]
    [InverseProperty("TblOrders")]
    public virtual TblProduct ProdidFkNavigation { get; set; }

    [ForeignKey("RegidFk")]
    [InverseProperty("TblOrders")]
    public virtual TblRegistration RegidFkNavigation { get; set; }

    [ForeignKey("StatusFk")]
    [InverseProperty("TblOrders")]
    public virtual TblStatus StatusFkNavigation { get; set; }

    [ForeignKey("UserFk")]
    [InverseProperty("TblOrders")]
    public virtual TblUser UserFkNavigation { get; set; }
}