// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblProvType")]
public partial class TblProvType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ProvTypeName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("ProvTypeFkNavigation")]
    public virtual ICollection<TblProvider> TblProviders { get; set; } = new List<TblProvider>();
}