// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblProdType")]
public partial class TblProdType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string ProdTypeName { get; set; }

    [StringLength(50)]
    public string ProdTypeCode { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("TypeFkNavigation")]
    public virtual ICollection<TblServProduct> TblServProducts { get; set; } = new List<TblServProduct>();
}