// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblProvider")]
[Index("ProvTypeFk", Name = "IX_tblProvider_ProvType_FK")]
public partial class TblProvider
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ProviderName { get; set; }

    [StringLength(255)]
    public string ProviderLogo { get; set; }

    [StringLength(7)]
    public string ProvMainColor { get; set; }

    [StringLength(15)]
    public string ProviderNo { get; set; }

    [Column("ProvType_FK")]
    public int ProvTypeFk { get; set; }

    [Required]
    [StringLength(50)]
    public string ProviderCode { get; set; }

    public bool AllowRtrn { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ProvTypeFk")]
    [InverseProperty("TblProviders")]
    public virtual TblProvType ProvTypeFkNavigation { get; set; }

    [InverseProperty("ProvidFkNavigation")]
    public virtual ICollection<TblDebtTrnsAct> TblDebtTrnsActs { get; set; } = new List<TblDebtTrnsAct>();

    [InverseProperty("ProviderIdFkNavigation")]
    public virtual ICollection<TblDepositOrder> TblDepositOrders { get; set; } = new List<TblDepositOrder>();

    [InverseProperty("Provider")]
    public virtual ICollection<TblDepositTrnx> TblDepositTrnxes { get; set; } = new List<TblDepositTrnx>();

    [InverseProperty("ProviderFkNavigation")]
    public virtual ICollection<TblProduct> TblProducts { get; set; } = new List<TblProduct>();

    [InverseProperty("ProviderFkNavigation")]
    public virtual ICollection<TblProviderAccOrBank> TblProviderAccOrBanks { get; set; } = new List<TblProviderAccOrBank>();

    [InverseProperty("ProviderFkNavigation")]
    public virtual ICollection<TblRegistration> TblRegistrations { get; set; } = new List<TblRegistration>();

    [InverseProperty("ServProvFkNavigation")]
    public virtual ICollection<TblServProduct> TblServProducts { get; set; } = new List<TblServProduct>();

    [InverseProperty("ServProvFkNavigation")]
    public virtual ICollection<TblServProvReg> TblServProvRegs { get; set; } = new List<TblServProvReg>();
}