// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblProdCat")]
public partial class TblProdCat
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string ProdCatName { get; set; }

    [StringLength(50)]
    public string ProdCatCode { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("CategoryFkNavigation")]
    public virtual ICollection<TblServProduct> TblServProducts { get; set; } = new List<TblServProduct>();
}