// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblProviderAccOrBank")]
[Index("ProviderFk", Name = "IX_tblProviderAccOrBank_Provider_FK")]
public partial class TblProviderAccOrBank
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string ProviderAccountNo { get; set; }

    [Column("Provider_FK")]
    public int ProviderFk { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ProviderFk")]
    [InverseProperty("TblProviderAccOrBanks")]
    public virtual TblProvider ProviderFkNavigation { get; set; }
}