// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblProduct")]
[Index("ProviderFk", Name = "IX_tblProduct_Provider_FK")]
[Index("UserFk", Name = "IX_tblProduct_User_FK")]
public partial class TblProduct
{
    [Key]
    public int Id { get; set; }

    [Column("User_FK")]
    public int UserFk { get; set; }

    [Required]
    [StringLength(50)]
    public string ProductCode { get; set; }

    [Required]
    [StringLength(100)]
    public string ProductName { get; set; }

    [Column("Provider_FK")]
    public int ProviderFk { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? BuyPrice { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? SellPrice { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? BuyComm { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? SellComm { get; set; }

    public int? Balance { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ProviderFk")]
    [InverseProperty("TblProducts")]
    public virtual TblProvider ProviderFkNavigation { get; set; }

    [InverseProperty("ProdidFkNavigation")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActs { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("ProdidFkNavigation")]
    public virtual ICollection<TblOrder> TblOrders { get; set; } = new List<TblOrder>();

    [ForeignKey("UserFk")]
    [InverseProperty("TblProducts")]
    public virtual TblUser UserFkNavigation { get; set; }
}