// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblRegistration")]
[Index("ProviderFk", Name = "IX_tblRegistration_Provider_fk")]
[Index("UserFk", Name = "IX_tblRegistration_User_FK")]
public partial class TblRegistration
{
    [Key]
    public int Id { get; set; }

    [Column("User_FK")]
    [Display(Name = "المـستـخدم")] //  <-- إضافة
    [Required(ErrorMessage = "الرجاء اختيار المستخدم")]
    public int UserFk { get; set; }

    [Required(ErrorMessage = "هذا الحقل مطلوب")]
    [Column("AccNameNO")]
    [StringLength(50)]
    [Display(Name = "اسم/رقم الحساب")] //  <-- إضافة
    public string AccNameNo { get; set; }

    [StringLength(50)]
    [Display(Name = "كود الحساب")] //  <-- إضافة
    [Required(ErrorMessage ="اكتب اسم التاجر و الشركة لتمييز الحساب")]
    public string Code { get; set; }

    [Column("Provider_fk")]
    [Display(Name = "مقدم الخدمة")] //  <-- إضافة
    [Required(ErrorMessage = "الرجاء اختيار مزود الخدمة")]
    public int ProviderFk { get; set; }

    [Display(Name = "الرصيد")] //  <-- إضافة
    [Range(0, double.MaxValue, ErrorMessage = "الرصيد يجب أن يكون قيمة موجبة")]
    public int Balance { get; set; }

    [Display(Name = "تاريخ البدء")] //  <-- إضافة
    [DataType(DataType.Date)] // <<< هذا مهم لعرض منتقي التاريخ
    public DateOnly? StartDate { get; set; }

    [Display(Name = "الحالة")] //  <-- إضافة
    public bool IsActive { get; set; }

    [ForeignKey("ProviderFk")]
    [InverseProperty("TblRegistrations")]
    public virtual TblProvider ProviderFkNavigation { get; set; }

    [InverseProperty("RecvrReg")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActRecvrRegs { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("SendrReg")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActSendrRegs { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("RegidFkNavigation")]
    public virtual ICollection<TblOrder> TblOrders { get; set; } = new List<TblOrder>();

    [ForeignKey("UserFk")]
    [InverseProperty("TblRegistrations")]
    [Display(Name = "التاجر")] //  <-- إضافة
    public virtual TblUser UserFkNavigation { get; set; }
}