// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblServTrnx")]
[Index("RecvrUserId", Name = "IX_tblServTrnx_RecvrUserID")]
[Index("ReferenceCode", Name = "IX_tblServTrnx_ReferenceCode")]
[Index("SenderUserId", Name = "IX_tblServTrnx_SenderUserID")]
[Index("SendrRegId", Name = "IX_tblServTrnx_SendrRegID")]
[Index("ServProdFk", Name = "IX_tblServTrnx_ServProd_FK")]
[Index("StatusFk", Name = "IX_tblServTrnx_Status_FK")]
public partial class TblServTrnx
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ReferenceCode { get; set; }

    [Column("SenderUserID")]
    public int SenderUserId { get; set; }

    [Column("SendrRegID")]
    public int SendrRegId { get; set; }

    [Column("RecvrUserID")]
    public int? RecvrUserId { get; set; }

    public int? BlncAmntOrderTrx { get; set; }

    public int SendrBlncBfr { get; set; }

    public int SendrBlncAftr { get; set; }

    public DateOnly TransDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAndTime { get; set; }

    [StringLength(50)]
    public string OrderNo { get; set; }

    [Column("ServProd_FK")]
    public int? ServProdFk { get; set; }

    [Required]
    [StringLength(50)]
    public string CustomerNoTrx { get; set; }

    public int SellPriceTrx { get; set; }

    public int? FeesTrx { get; set; }

    public int TotalPriceTrx { get; set; }

    [StringLength(255)]
    public string CnfrmNumOrPic { get; set; }

    [Column("Status_FK")]
    public int StatusFk { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [ForeignKey("RecvrUserId")]
    [InverseProperty("TblServTrnxRecvrUsers")]
    public virtual TblUser RecvrUser { get; set; }

    [ForeignKey("SenderUserId")]
    [InverseProperty("TblServTrnxSenderUsers")]
    public virtual TblUser SenderUser { get; set; }

    [ForeignKey("SendrRegId")]
    [InverseProperty("TblServTrnxes")]
    public virtual TblServProvReg SendrReg { get; set; }

    [ForeignKey("ServProdFk")]
    [InverseProperty("TblServTrnxes")]
    public virtual TblServProduct ServProdFkNavigation { get; set; }

    [ForeignKey("StatusFk")]
    [InverseProperty("TblServTrnxes")]
    public virtual TblStatus StatusFkNavigation { get; set; }
}