// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblStatusReason")]
[Index("StatusIdFk", Name = "IX_tblStatusReason_StatusID_FK")]
public partial class TblStatusReason
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(250)]
    public string StatusReason { get; set; }

    [Column("StatusID_FK")]
    public int StatusIdFk { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("StatusIdFk")]
    [InverseProperty("TblStatusReasons")]
    public virtual TblStatus StatusIdFkNavigation { get; set; }
}