// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblServOrder")]
[Index("BillingNo", Name = "IX_tblServOrder_BillingNo")]
[Index("OrderNo", Name = "IX_tblServOrder_OrderNo")]
[Index("ServProdFk", Name = "IX_tblServOrder_ServProd_FK")]
[Index("StatusFk", Name = "IX_tblServOrder_Status_FK")]
[Index("UserIdFk", Name = "IX_tblServOrder_UserID_FK")]
public partial class TblServOrder
{
    [Key]
    public int Id { get; set; }

    [Column("UserID_FK")]
    public int UserIdFk { get; set; }

    [Required]
    [StringLength(50)]
    public string OrderNo { get; set; }

    [Column("ServProd_FK")]
    public int ServProdFk { get; set; }

    public int IndebtBefore { get; set; }

    public int BlncAmntOrder { get; set; }

    public int SellPrice { get; set; }

    public int? Fees { get; set; }

    public int TotalPrice { get; set; }

    public int IndebtAfter { get; set; }

    public DateOnly TransDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateAndTime { get; set; }

    [Required]
    [StringLength(50)]
    public string BillingNo { get; set; }

    [Column("Status_FK")]
    public int StatusFk { get; set; }

    [ForeignKey("ServProdFk")]
    [InverseProperty("TblServOrders")]
    public virtual TblServProduct ServProdFkNavigation { get; set; }

    [ForeignKey("StatusFk")]
    [InverseProperty("TblServOrders")]
    public virtual TblStatus StatusFkNavigation { get; set; }

    [ForeignKey("UserIdFk")]
    [InverseProperty("TblServOrders")]
    public virtual TblUser UserIdFkNavigation { get; set; }
}