// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblServProvReg")]
[Index("ServProvFk", Name = "IX_tblServProvReg_ServProv_FK")]
[Index("UserFk", Name = "IX_tblServProvReg_User_FK")]
public partial class TblServProvReg
{
    [Key]
    public int Id { get; set; }

    [Column("User_FK")]
    public int UserFk { get; set; }

    [Required]
    [StringLength(20)]
    public string ServNo { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [Column("ServProv_FK")]
    public int ServProvFk { get; set; }

    public int? Balance { get; set; }

    public DateOnly? StartDate { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ServProvFk")]
    [InverseProperty("TblServProvRegs")]
    public virtual TblProvider ServProvFkNavigation { get; set; }

    [InverseProperty("SendrReg")]
    public virtual ICollection<TblServTrnx> TblServTrnxes { get; set; } = new List<TblServTrnx>();

    [ForeignKey("UserFk")]
    [InverseProperty("TblServProvRegs")]
    public virtual TblUser UserFkNavigation { get; set; }
}