// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblServProduct")]
[Index("CategoryFk", Name = "IX_tblServProduct_Category_FK")]
[Index("ServProvFk", Name = "IX_tblServProduct_ServProv_FK")]
[Index("TypeFk", Name = "IX_tblServProduct_Type_FK")]
[Index("UserIdFk", Name = "IX_tblServProduct_UserID_FK")]
public partial class TblServProduct
{
    [Key]
    public int Id { get; set; }

    [Column("UserID_FK")]
    public int? UserIdFk { get; set; }

    [Required]
    [StringLength(50)]
    public string ServProdCode { get; set; }

    [Required]
    [StringLength(100)]
    public string ServProdName { get; set; }

    [Column("ServProv_FK")]
    public int ServProvFk { get; set; }

    [Column("Category_FK")]
    public int CategoryFk { get; set; }

    [Column("Type_FK")]
    public int TypeFk { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? ServProdBuyPrice { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? ServProdFees { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? ServProdSellPrice { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? ServProdBuyComm { get; set; }

    [Column(TypeName = "decimal(8, 4)")]
    public decimal? ServProdSellComm { get; set; }

    public int? ServProdBalance { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("CategoryFk")]
    [InverseProperty("TblServProducts")]
    public virtual TblProdCat CategoryFkNavigation { get; set; }

    [ForeignKey("ServProvFk")]
    [InverseProperty("TblServProducts")]
    public virtual TblProvider ServProvFkNavigation { get; set; }

    [InverseProperty("ServProdFkNavigation")]
    public virtual ICollection<TblServOrder> TblServOrders { get; set; } = new List<TblServOrder>();

    [InverseProperty("ServProdFkNavigation")]
    public virtual ICollection<TblServTrnx> TblServTrnxes { get; set; } = new List<TblServTrnx>();

    [ForeignKey("TypeFk")]
    [InverseProperty("TblServProducts")]
    public virtual TblProdType TypeFkNavigation { get; set; }

    [ForeignKey("UserIdFk")]
    [InverseProperty("TblServProducts")]
    public virtual TblUser UserIdFkNavigation { get; set; }
}