// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblStatus")]
public partial class TblStatus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string StatusName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<TblDepositOrder> TblDepositOrders { get; set; } = new List<TblDepositOrder>();

    [InverseProperty("StatusIdFkNavigation")]
    public virtual ICollection<TblDepositTrnx> TblDepositTrnxes { get; set; } = new List<TblDepositTrnx>();

    [InverseProperty("StatusFkNavigation")]
    public virtual ICollection<TblOrder> TblOrders { get; set; } = new List<TblOrder>();

    [InverseProperty("StatusFkNavigation")]
    public virtual ICollection<TblServOrder> TblServOrders { get; set; } = new List<TblServOrder>();

    [InverseProperty("StatusFkNavigation")]
    public virtual ICollection<TblServTrnx> TblServTrnxes { get; set; } = new List<TblServTrnx>();

    [InverseProperty("StatusIdFkNavigation")]
    public virtual ICollection<TblStatusReason> TblStatusReasons { get; set; } = new List<TblStatusReason>();
}