// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblTransType")]
public partial class TblTransType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string TransTypeName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("TransType")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActs { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("TransType")]
    public virtual ICollection<TblDebtTrnsAct> TblDebtTrnsActs { get; set; } = new List<TblDebtTrnsAct>();

    [InverseProperty("TransType")]
    public virtual ICollection<TblDrwerTransAction> TblDrwerTransActions { get; set; } = new List<TblDrwerTransAction>();
}