// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblUser")]
[Index("BranchFk", Name = "IX_tblUser_Branch_FK")]
[Index("CompanyFk", Name = "IX_tblUser_Company_FK")]
[Index("ContactNo", Name = "IX_tblUser_ContactNo")]
[Index("DirctionFk", Name = "IX_tblUser_Dirction_fk")]
[Index("DistrectFk", Name = "IX_tblUser_Distrect_FK")]
[Index("GovernateFk", Name = "IX_tblUser_Governate_FK")]
[Index("UserTypeFk", Name = "IX_tblUser_UserType_fk")]
public partial class TblUser
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [Required]
    [StringLength(20)]
    public string ContactNo { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(256)]
    public string Password { get; set; }

    [StringLength(255)]
    public string Photo { get; set; }

    [StringLength(250)]
    public string Address { get; set; }

    [StringLength(100)]
    public string Street { get; set; }

    [Column("Distrect_FK")]
    public int? DistrectFk { get; set; }

    [Column("Governate_FK")]
    public int? GovernateFk { get; set; }

    [Column("NAID")]
    [StringLength(14)]
    public string Naid { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? SubEndDate { get; set; }

    [Column("UserType_fk")]
    public int UserTypeFk { get; set; }

    [Column("Dirction_fk")]
    public int? DirctionFk { get; set; }

    public int? Priority { get; set; }

    [Column("Company_FK")]
    public int? CompanyFk { get; set; }

    [Column("Branch_FK")]
    public int? BranchFk { get; set; }

    public int? ParentUser { get; set; }

    [StringLength(50)]
    public string UserCode { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("BranchFk")]
    [InverseProperty("TblUsers")]
    public virtual TblBranch BranchFkNavigation { get; set; }

    [ForeignKey("CompanyFk")]
    [InverseProperty("TblUsers")]
    public virtual TblCompany CompanyFkNavigation { get; set; }

    [ForeignKey("DirctionFk")]
    [InverseProperty("TblUsers")]
    public virtual TblDirction DirctionFkNavigation { get; set; }

    [ForeignKey("DistrectFk")]
    [InverseProperty("TblUsers")]
    public virtual TblDistrict DistrectFkNavigation { get; set; }

    [ForeignKey("GovernateFk")]
    [InverseProperty("TblUsers")]
    public virtual TblGovernate GovernateFkNavigation { get; set; }

    [InverseProperty("UserIdFkNavigation")]
    public virtual ICollection<TblAccount> TblAccounts { get; set; } = new List<TblAccount>();

    [InverseProperty("RecvrUser")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActRecvrUsers { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("SendrUser")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActSendrUsers { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblBlncTrnsAct> TblBlncTrnsActUserFkNavigations { get; set; } = new List<TblBlncTrnsAct>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblDebtTrnsAct> TblDebtTrnsActs { get; set; } = new List<TblDebtTrnsAct>();

    [InverseProperty("DepositForNavigation")]
    public virtual ICollection<TblDepositOrder> TblDepositOrderDepositForNavigations { get; set; } = new List<TblDepositOrder>();

    [InverseProperty("UserIdFkNavigation")]
    public virtual ICollection<TblDepositOrder> TblDepositOrderUserIdFkNavigations { get; set; } = new List<TblDepositOrder>();

    [InverseProperty("DepositForNavigation")]
    public virtual ICollection<TblDepositTrnx> TblDepositTrnxDepositForNavigations { get; set; } = new List<TblDepositTrnx>();

    [InverseProperty("UserIdFkNavigation")]
    public virtual ICollection<TblDepositTrnx> TblDepositTrnxUserIdFkNavigations { get; set; } = new List<TblDepositTrnx>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblDrawer> TblDrawers { get; set; } = new List<TblDrawer>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblOrder> TblOrders { get; set; } = new List<TblOrder>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblProduct> TblProducts { get; set; } = new List<TblProduct>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblRegistration> TblRegistrations { get; set; } = new List<TblRegistration>();

    [InverseProperty("UserIdFkNavigation")]
    public virtual ICollection<TblServOrder> TblServOrders { get; set; } = new List<TblServOrder>();

    [InverseProperty("UserIdFkNavigation")]
    public virtual ICollection<TblServProduct> TblServProducts { get; set; } = new List<TblServProduct>();

    [InverseProperty("UserFkNavigation")]
    public virtual ICollection<TblServProvReg> TblServProvRegs { get; set; } = new List<TblServProvReg>();

    [InverseProperty("RecvrUser")]
    public virtual ICollection<TblServTrnx> TblServTrnxRecvrUsers { get; set; } = new List<TblServTrnx>();

    [InverseProperty("SenderUser")]
    public virtual ICollection<TblServTrnx> TblServTrnxSenderUsers { get; set; } = new List<TblServTrnx>();

    [ForeignKey("UserTypeFk")]
    [InverseProperty("TblUsers")]
    public virtual TblUserType UserTypeFkNavigation { get; set; }
}