// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseAccess.Models;

[Table("tblUserType")]
public partial class TblUserType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(25)]
    public string UserTypeName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("AdminProfileFkNavigation")]
    public virtual ICollection<TblAdmin> TblAdmins { get; set; } = new List<TblAdmin>();

    [InverseProperty("UserTypeFkNavigation")]
    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
}